[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediction_market = "3UbWs4nuaMKoGkjhLuoLdgVESe9YkjjpDMBaZsz33cVt"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
