[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "D2GqUbaoJc2u1MPnx19AJf9gA4y22GDv6C88oP4j1LPM"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
