[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stableswap = "4qXgy46E7G1ziEafdAkjra4f3KZCqWxpgRhiEQykgcHq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
